### ISSUE TITLE
Date for holland backup 

### ISSUE THREAD

**Issue by Bumblebee-Man** [rcbops/ansible-lxc-rpc#136]
Date for holland backup is set to run every Thursday. Holland should run daily. 

ansible-lxc-rpc / rpc_deployment / roles / rpc_support_holland / tasks / holland.yml

```
- name: Create holland backup cron job
  cron:
  name: "holland-backup"
  minute: "{{ 59|random }}"
  weekday: "{{ 6|random }}"
```
