### ISSUE TITLE
safe upgrade is upgrading the kernel

### ISSUE THREAD

**Issue by cloudnull** [rcbops/ansible-lxc-rpc#92]
When the setup-common role runs a safe-upgrade is run to ensure all of the packages that are determined to be safely upgradable are up-to-date. Sadly the ansible apt module uses aptitude to perform this upgrade which attempts to bring in new kernels as they become available.  Presently we are dep'ing on `kernel 3.13.0-34-generic` and the new stable kernel for Ubuntu 14.04.01 `kernel 3.13.0-35-generic`.  It would seem that this is going to be a never ending battle of incremental kernel releases.  If we are not going to be deploying a repository of frozen packages at this time we may need change the kernel check to set on the version and allow for kernel releases of >= `34`.

**Comment by byronmccollum** [comment]
Instead of running `uname -r`, the same value is in the `ansible_kernel` fact.

Additionally, is this just doing a string comparison? Maybe something like this...?

```
---
# This playbook checks kernel version

- name: Check Kernel Version
  hosts: all
  gather_facts: yes
  vars:
    required_kernel_version: '3.13.0'
    required_kernel_patch: '34'
    required_kernel_variant: 'generic'
  tasks:
    - name: Get Kernel Parts
      set_fact:
        kernel_version: "{{ ansible_kernel.split('-')[0] }}"
        kernel_patch: "{{ ansible_kernel.split('-')[1] }}"
        kernel_variant: "{{ ansible_kernel.split('-')[2] }}"

    - name: Check Kernel Version
      fail:
        msg: >
          Wrong kernel Version found
          [ {{ ansible_kernel }} < {{ [required_kernel_version, required_kernel_patch, required_kernel_variant]|join('-') }} ]
          Resolve this issue before continuing.
      when: kernel_version | version_compare(required_kernel_version, '<') or kernel_patch | version_compare(required_kernel_patch, '<') or kernel_variant != required_kernel_variant
```
